// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/Badge.vue')['default']
    ButtonInput: typeof import('./src/components/form/ButtonInput.vue')['default']
    ClinicHeader: typeof import('./src/components/clinics/ClinicHeader.vue')['default']
    ClinicRequest: typeof import('./src/components/clinics/ClinicRequest.vue')['default']
    ClinicsSearchFilters: typeof import('./src/components/clinics/ClinicsSearchFilters.vue')['default']
    ClinicsSearchResults: typeof import('./src/components/clinics/ClinicsSearchResults.vue')['default']
    ClinicsSlideOver: typeof import('./src/components/admin/slideovers/ClinicsSlideOver.vue')['default']
    Combobox: typeof import('./src/components/landing/form/Combobox.vue')['default']
    CTA: typeof import('./src/components/landing/CTA.vue')['default']
    DarkToggle: typeof import('./src/components/admin/DarkToggle.vue')['default']
    DocForm: typeof import('./src/components/landing/DocForm.vue')['default']
    DocsSearchFilters: typeof import('./src/components/docs/DocsSearchFilters.vue')['default']
    DocsSearchResults: typeof import('./src/components/docs/DocsSearchResults.vue')['default']
    DocsSlideOver: typeof import('./src/components/admin/slideovers/DocsSlideOver.vue')['default']
    Dropdown: typeof import('./src/components/landing/form/Dropdown.vue')['default']
    EditableTable: typeof import('./src/components/admin/EditableTable.vue')['default']
    EditSpecialization: typeof import('./src/components/EditSpecialization.vue')['default']
    FAQ: typeof import('./src/components/landing/FAQ.vue')['default']
    Footer: typeof import('./src/components/landing/Footer.vue')['default']
    Hero: typeof import('./src/components/landing/Hero.vue')['default']
    IconInput: typeof import('./src/components/form/IconInput.vue')['default']
    LangToggle: typeof import('./src/components/admin/LangToggle.vue')['default']
    LoginFormClinics: typeof import('./src/components/auth/LoginFormClinics.vue')['default']
    LoginFormDocs: typeof import('./src/components/auth/LoginFormDocs.vue')['default']
    Old_Hero: typeof import('./src/components/landing/Old_Hero.vue')['default']
    RegisterFormClinics: typeof import('./src/components/auth/RegisterFormClinics.vue')['default']
    RegisterFormDocs: typeof import('./src/components/auth/RegisterFormDocs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./src/components/auth/SignInForm.vue')['default']
    SlideOver: typeof import('./src/components/admin/slideovers/SlideOver.vue')['default']
    Stars: typeof import('./src/components/landing/form/Stars.vue')['default']
    SuccessPopup: typeof import('./src/components/clinics/SuccessPopup.vue')['default']
    Switch: typeof import('./src/components/landing/form/Switch.vue')['default']
    TestResults: typeof import('./src/components/TestResults.vue')['default']
    VacancySlideOver: typeof import('./src/components/admin/slideovers/VacancySlideOver.vue')['default']
    VerifiedSlideOver: typeof import('./src/components/admin/slideovers/VerifiedSlideOver.vue')['default']
  }
}

export {}
