// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Combobox: typeof import('./src/components/landing/form/Combobox.vue')['default']
    DarkToggle: typeof import('./src/components/admin/DarkToggle.vue')['default']
    DocForm: typeof import('./src/components/landing/DocForm.vue')['default']
    Footer: typeof import('./src/components/landing/Footer.vue')['default']
    Hero: typeof import('./src/components/landing/Hero.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    LangToggle: typeof import('./src/components/admin/LangToggle.vue')['default']
    Navbar: typeof import('./src/components/admin/Navbar.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./src/components/auth/SignInForm.vue')['default']
    SlideOver: typeof import('./src/components/admin/SlideOver.vue')['default']
    Stars: typeof import('./src/components/landing/form/Stars.vue')['default']
    Switch: typeof import('./src/components/landing/form/Switch.vue')['default']
    TestResults: typeof import('./src/components/TestResults.vue')['default']
  }
}

export {}
