<template>
  <div id="doc_form" class="bg-gray-50">
    <div class="max-w-7xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
      <div class="relative bg-white">
        <h2 class="sr-only">Contact us</h2>

        <div class="grid grid-cols-1 lg:grid-cols-3">
          <!-- Contact information -->
          <div class="relative overflow-hidden py-10 px-6 bg-slate-700 sm:px-10 xl:p-12">
            <div class="absolute inset-0 pointer-events-none sm:hidden" aria-hidden="true">
              <svg class="absolute inset-0 w-full h-full" width="343" height="388" viewBox="0 0 343 388" fill="none" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg">
                <path d="M-99 461.107L608.107-246l707.103 707.107-707.103 707.103L-99 461.107z" fill="url(#linear1)" fill-opacity=".1" />
                <defs>
                  <linearGradient id="linear1" x1="254.553" y1="107.554" x2="961.66" y2="814.66" gradientUnits="userSpaceOnUse">
                    <stop stop-color="#fff" />
                    <stop offset="1" stop-color="#fff" stop-opacity="0" />
                  </linearGradient>
                </defs>
              </svg>
            </div>
            <div class="hidden absolute top-0 right-0 bottom-0 w-1/2 pointer-events-none sm:block lg:hidden" aria-hidden="true">
              <svg class="absolute inset-0 w-full h-full" width="359" height="339" viewBox="0 0 359 339" fill="none" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg">
                <path d="M-161 382.107L546.107-325l707.103 707.107-707.103 707.103L-161 382.107z" fill="url(#linear2)" fill-opacity=".1" />
                <defs>
                  <linearGradient id="linear2" x1="192.553" y1="28.553" x2="899.66" y2="735.66" gradientUnits="userSpaceOnUse">
                    <stop stop-color="#fff" />
                    <stop offset="1" stop-color="#fff" stop-opacity="0" />
                  </linearGradient>
                </defs>
              </svg>
            </div>
            <div class="hidden absolute top-0 right-0 bottom-0 w-1/2 pointer-events-none lg:block" aria-hidden="true">
              <svg class="absolute inset-0 w-full h-full" width="160" height="678" viewBox="0 0 160 678" fill="none" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg">
                <path d="M-161 679.107L546.107-28l707.103 707.107-707.103 707.103L-161 679.107z" fill="url(#linear3)" fill-opacity=".1" />
                <defs>
                  <linearGradient id="linear3" x1="192.553" y1="325.553" x2="899.66" y2="1032.66" gradientUnits="userSpaceOnUse">
                    <stop stop-color="#fff" />
                    <stop offset="1" stop-color="#fff" stop-opacity="0" />
                  </linearGradient>
                </defs>
              </svg>
            </div>
            <h3 class="text-xl font-medium text-white">Contact information</h3>
            <p class="mt-6 text-base text-slate-50 max-w-3xl">Our team is always there to help you and will always answer within 1 business day</p>
            <dl class="mt-8 space-y-6">
              <dt><span class="sr-only">Phone number</span></dt>
              <dd class="flex text-base text-slate-50">
                <PhoneIcon class="flex-shrink-0 w-6 h-6 text-slate-200" aria-hidden="true" />
                <span class="ml-3">+49 (0) 33112 313 12</span>
              </dd>
              <dt><span class="sr-only">Email</span></dt>
              <dd class="flex text-base text-slate-50">
                <MailIcon class="flex-shrink-0 w-6 h-6 text-slate-200" aria-hidden="true" />
                <span class="ml-3">support@medching.com</span>
              </dd>
            </dl>
          </div>

          <!-- Contact form -->
          <div class="py-10 px-6 sm:px-10 lg:col-span-2 xl:p-12">
            <h3 class="text-2xl font-medium text-gray-900">Find your dream job</h3>
            <div class="mt-6 grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8">
              <div>
                <label for="first-name" class="block text-sm font-medium text-gray-900">First name</label>
                <div class="mt-1">
                  <input v-model="store.form_inputs.first_name" required type="text" name="first-name" id="first-name" autocomplete="given-name" class="py-3 px-4 block w-full shadow-sm text-gray-900 focus:ring-slate-500 focus:border-slate-500 border-gray-300 rounded-md" />
                </div>
              </div>
              <div>
                <label for="last-name" class="block text-sm font-medium text-gray-900">Last name</label>
                <div class="mt-1">
                  <input v-model="store.form_inputs.last_name" required type="text" name="last-name" id="last-name" autocomplete="family-name" class="py-3 px-4 block w-full shadow-sm text-gray-900 focus:ring-slate-500 focus:border-slate-500 border-gray-300 rounded-md" />
                </div>
              </div>
              <div>
                <div class="flex justify-between">
                  <label for="email" class="block text-sm font-medium text-gray-900">Email</label>
                </div>
                <div class="mt-1">
                  <input v-model="store.form_inputs.email" required id="email" name="email" type="email" autocomplete="email" class="py-3 px-4 block w-full shadow-sm text-gray-900 focus:ring-slate-500 focus:border-slate-500 border-gray-300 rounded-md" />
                </div>
              </div>
              <div>
                <div class="flex justify-between">
                  <label for="phone" class="block text-sm font-medium text-gray-900">Phone</label>
                </div>
                <div class="mt-1">
                  <input v-model="store.form_inputs.phone" required type="text" name="phone" id="phone" autocomplete="tel" class="py-3 px-4 block w-full shadow-sm text-gray-900 focus:ring-slate-500 focus:border-slate-500 border-gray-300 rounded-md" aria-describedby="phone-optional" />
                </div>
              </div>
              <div class="sm:col-span-2">
                 <label class="block text-sm font-medium text-gray-900">State</label>
                <Combobox @change="({ name }) => store.location_inputs.state = name" placeholder="Search State..." :options="states"/>
              </div>
              <div class="sm:col-span-2">
                 <label class="block text-sm font-medium text-gray-900">City</label>
                <Combobox @change="({ name }) => store.location_inputs.city = name" placeholder="Search City..." :options="cities"/>
              </div>
                <div class="sm:col-span-2">
                   <label class="block text-sm font-medium text-gray-900">Position</label>
                  <Combobox @change="({ id }) => store.location_inputs.position = id" placeholder="Search Position..." :options="positions"/>
                </div>
              <div class="sm:col-span-2">
                <label class="block text-sm font-medium text-gray-900">Specialization</label>
                <Combobox @change="({ id }) => store.location_inputs.specialization = id" :show_3_suggestions="true" placeholder="Search Specializations..." :options="specializations"/>
              </div>
              <div class="col-span-full">
                <div class="flex justify-between">
                  <label for="radius" class="block text-sm font-medium text-gray-900">Radius (km)</label>
                  <span id="radius-description" class="text-sm text-gray-500">in km</span>
                </div>
                <div class="mt-1">
                  <input type="number" min="1" name="radius" id="radius" autocomplete="radius" class="py-3 px-4 block w-full shadow-sm text-gray-900 focus:ring-slate-500 focus:border-slate-500 border-gray-300 rounded-md" aria-describedby="radius-description" />
                </div>
              </div>
              <div class="sm:col-span-2 z-10 flex flex-col">
                <label class="block text-sm font-medium text-gray-900">Stars left</label>
                <Stars :readonly="true" name="xxx" :modelValue="max_stars - stars_given" :max="max_stars" />
                <button class="flex justify-center w-20 bg-gray-600 text-white px-3 py-2 my-2 rounded" @click="reset">Reset</button>
              </div>
              <div class="sm:col-span-2 z-10" v-for="p in preferences">
                <label class="block text-sm font-medium text-gray-900">{{ p.name }}</label>
                <Stars :name="p.name" :max="max_stars" :readonly="stars_given === max_stars" @input="(v) => v + stars_given <= max_stars ? store.user_inputs[p.field] = v : store.user_inputs[p.field] = (max_stars - stars_given)" :modelValue="store.user_inputs[p.field]" />
              </div>
              <div class="sm:col-span-2">
                <div class="flex justify-between">
                  <label for="message" class="block text-sm font-medium text-gray-900">Message</label>
                  <span id="message-max" class="text-sm text-gray-500">Max. 500 characters</span>
                </div>
                <div class="mt-1">
                  <textarea id="message" name="message" rows="4" class="py-3 px-4 block w-full shadow-sm text-gray-900 focus:ring-slate-500 focus:border-slate-500 border border-gray-300 rounded-md" aria-describedby="message-max" />
                </div>
              </div>
              <div class="col-span-full flex">

                <button type="button" @click="store.showResults = true" :disabled="need_more_input" class="disabled:cursor-not-allowed disabled:bg-gray-900 mr-4 w-full inline-flex items-center justify-center px-6 py-3 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-slate-600 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-slate-500 sm:w-auto">
                  Submit
                </button>
                <Switch @change="(v) => agreed_to_terms = v" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { MailIcon, PhoneIcon } from '@heroicons/vue/outline'
import { useStore } from '@/store/index'

const store = useStore()

const max_stars = ref(5)
const stars_given = computed(() => Object.values(store.user_inputs).reduce((a,b)=>a+b), 0)
const agreed_to_terms = ref(false)
const need_more_input = computed(() => agreed_to_terms.value == false || !store.form_inputs.first_name.length || !store.form_inputs.last_name.length || !store.form_inputs.email.length || !store.form_inputs.phone.length);

const reset = () => {
  store.user_inputs = {
    work_life: 0,
    career: 0,
    work_quality: 0,
  }
}

const positions = [
  { id: 1, name: 'Berufserlaubnis' },
  { id: 2, name: 'Assistenzarzt' },
  { id: 3, name: 'Facharzt' },
  { id: 4, name: 'Oberarzt' },
  { id: 5, name: 'Ltd. Oberarzt' }]
const preferences = [
  { field: 'work_life', name: "Work-Life Balance"},
  { field: 'career', name: "Karrieremöglichkeiten"},
  { field: 'work_quality', name: "Arbeitsqualität"}]
const states = [
  { name: "Baden-Württemberg" },
  { name: "Bayern" },
  { name: "Berlin" },
  { name: "Brandenburg" },
  { name: "Bremen" },
  { name: "Hamburg" },
  { name: "Hessen" },
  { name: "Mecklenburg-Vorpommern" },
  { name: "Niedersachsen" },
  { name: "Nordrhein-Westfalen" },
  { name: "Rheinland-Pfalz" },
  { name: "Saarland" },
  { name: "Sachsen" },
  { name: "Sachsen-Anhalt" },
  { name: "Schleswig-Holstein" },
  { name: "Thüringen" }]
const specializations = [
  { id: 1, name: 'Allgemeine Chirurgie ' },
  { id: 2, name: 'Allgemeine Chirurgie  - Intensivmedizin ' },
  { id: 3, name: 'Allgemeine Chirurgie  - Schwerpunkt Abdominal- und Gefäßchirurgie ' },
  { id: 4, name: 'Allgemeine Chirurgie - Gefäßchirurgie' },
  { id: 5, name: 'Allgemeine Chirurgie - Handchirurgie' },
  { id: 6, name: 'Allgemeine Chirurgie - Kinderchirurgie' },
  { id: 7, name: 'Allgemeine Chirurgie - Plastische Chirurgie' },
  { id: 8, name: 'Allgemeine Chirurgie - Thoraxchirurgie' },
  { id: 9, name: 'Allgemeine Chirurgie - Unfallchirurgie' },
  { id: 10, name: 'Allgemeine Psychiatrie' },
  { id: 11, name: 'Allgemeine Psychiatrie - Nachtklinik ' },
  { id: 12, name: 'Allgemeine Psychiatrie - Forensische Behandlung' },
  { id: 13, name: 'Allgemeine Psychiatrie - Gerontopsychiatrie' },
  { id: 14, name: 'Allgemeine Psychiatrie - Gerontopsychiatrie, Tagesklinik' },
  { id: 15, name: 'Allgemeine Psychiatrie Kinder- und Jugendpsychiatrie' },
  { id: 16, name: 'Allgemeine Psychiatrie - Neurologie' },
  { id: 17, name: 'Allgemeine Psychiatrie - Psychosomatik/Psychotherapie' },
  { id: 18, name: 'Allgemeine Psychiatrie - Schwerpunkt Suchtbehandlung ' },
  { id: 19, name: 'Allgemeine Psychiatrie - Schwerpunkt Suchtbehandlung, Tagesklinik ' },
  { id: 20, name: 'Allgemeine Psychiatrie, Tagesklinik ' },
  { id: 21, name: 'Angiologie' },
  { id: 22, name: 'Augenheilkunde ' },
  { id: 23, name: 'Chirurgie - Orthopädie ' },
  { id: 24, name: 'Dermatologie' },
  { id: 25, name: 'Dermatologie - Tagesklinik ' },
  { id: 26, name: 'Endokriminologie' },
  { id: 27, name: 'Frauennheilkunde und Geburtshilfe' },
  { id: 28, name: 'Frauenheilkunde - Endokriminologie ' },
  { id: 29, name: 'Frauenheilkunde - Hämatologie und internistische Onkologie ' },
  { id: 30, name: 'Gastroenterologie ' },
  { id: 31, name: 'Gastroenterologie - Pädiatrie ' },
  { id: 32, name: 'Gefäßchirurgie ' },
  { id: 34, name: 'Geriatrie' },
  { id: 35, name: 'Geriatrie, Nachtklinik ' },
  { id: 36, name: 'Geriatrie, Tagesklinik ' },
  { id: 37, name: 'Hals-Nasen-Ohrenheilkunde ' },
  { id: 38, name: 'Hämatologie und internistische Onkologie - Pädiatrie ' },
  { id: 39, name: 'Hämatologie und internistische Onkologie - Strahlenheilkunde ' },
  { id: 40, name: 'Heiltherapeutische Abteilung ' },
  { id: 41, name: 'Herzchirurgie - Intensivmedizin ' },
  { id: 42, name: 'Herzchirurgie und internistische Onkologie ' },
  { id: 43, name: 'Innere Medizin' },
  { id: 44, name: 'Innere Medizin - Coloproktologie' },
  { id: 45, name: 'Innere Medizin - Diabetes' },
  { id: 46, name: 'Innere Medizin - Endokrinologie ' },
  { id: 47, name: 'Innere Medizin - Gastroenterologie ' },
  { id: 48, name: 'Innere Medizin - Geriatrie' },
  { id: 49, name: 'Innere Medizin - Hämatologie und internistische Onkologie ' },
  { id: 50, name: 'Innere Medizin - Infektionskrankheiten ' },
  { id: 51, name: 'Innere Medzin - Kardiologie ' },
  { id: 52, name: 'Innere Medzin - Lungen- und Brochialheilkunde' },
  { id: 53, name: 'Innere Medizin - Naturheilkunde ' },
  { id: 54, name: 'Innere Medizin - Nephrologie' },
  { id: 55, name: 'Innere Medzin - Pneumologie ' },
  { id: 56, name: 'Innere Medizin - Rheumatologie ' },
  { id: 57, name: 'Innere Medizin - Schlaganfallpatienten ' },
  { id: 58, name: 'Innere Medizin - Tumorforschung ' },
  { id: 59, name: 'Intensivmedizin, Anästhesie' },
  { id: 60, name: 'Intensivmedizin Orthopädie - Reumatologie ' },
  { id: 61, name: 'Intensivmedizin - Chirurgie ' },
  { id: 62, name: 'Intensivmedizin - Herzchirurgie ' },
  { id: 63, name: 'Intensivmedizin - Innere Medizin ' },
  { id: 64, name: 'Intensivmedizin - Neurochirurgie ' },
  { id: 65, name: 'Intensivmedizin - Neurologie ' },
  { id: 66, name: 'Intensivmedizin - Pädiatrie' },
  { id: 67, name: 'Intensivmedizin - Urologie' },
  { id: 68, name: 'Kardiologie' },
  { id: 69, name: 'Kinder- und Jugendpsychiatrie' },
  { id: 70, name: 'Kinder- und Jugendpsychiatrie, Nachtklinik' },
  { id: 71, name: 'Kinder- und Jugendpsychiatrie, Tagesklinik ' },
  { id: 72, name: 'Kinderchirurgie ' },
  { id: 73, name: 'Kinderkardiologie ' },
  { id: 74, name: 'Kinderkardiologie - Intensivmedizin ' },
  { id: 75, name: 'Langzeitbereich Kinder ' },
  { id: 76, name: 'Lungen- und Brochialheilkunde ' },
  { id: 77, name: 'Neonatologie - Früh- und Neugeborenmedizin' },
  { id: 78, name: 'Nephrologie' },
  { id: 79, name: 'Neurochirurgie' },
  { id: 80, name: 'Neurologie' },
  { id: 81, name: 'Neurologie - Pädiatrie' },
  { id: 82, name: 'Neurologie - Schlaganfallpatienten ' },
  { id: 83, name: 'Nuklearmedizin ' },
  { id: 84, name: 'Nuklearmedizin - Strahlenheilkunde ' },
  { id: 85, name: 'Operative Intensivmedzin - Chirurgie ' },
  { id: 86, name: 'Orthopädie - Chirurgie ' },
  { id: 87, name: 'Senologie und Brustzentrum' },
  { id: 88, name: 'Palliativmedizin ' },
  { id: 89, name: 'Pädieatrie - Endokrinologie ' },
  { id: 90, name: 'Pädietrie - Gastroenterologie' },
  { id: 91, name: 'Pädiatrie - Hämatologie und internistische Onkologie ' },
  { id: 92, name: 'Pädiatrie - Kinderkardiologie' },
  { id: 93, name: 'Pädiatrie - Kinderneurologie ' },
  { id: 94, name: 'Pädiatrie - Lungen- und Bronchialheilkunde ' },
  { id: 95, name: 'Pädiatrie - Neonatologie' },
  { id: 96, name: 'Pädiatrie - Nephrologie' },
  { id: 97, name: 'Pädiatrie - Rheumatologie' },
  { id: 98, name: 'Plastische Chirurgie' },
  { id: 99, name: 'Pneumologie' },
  { id: 100, name: 'Psychosomatik - Psychotherapie' },
  { id: 101, name: 'Psychosomatik - Psychotherapie, Nachtklinik' },
  { id: 102, name: 'Psychosomatik - Psychotherapie, Tagesklinik' },
  { id: 103, name: 'Psychosotamik - Kinder- und Jugendpsychosomatik' },
  { id: 104, name: 'Pädiatrie' },
  { id: 105, name: 'Radiologie' },
  { id: 106, name: 'Pheumatologie' },
  { id: 107, name: 'Schmerztherapie' },
  { id: 108, name: 'Sonstige Fachabteilung ' },
  { id: 109, name: 'Strahlenheilkunde' },
  { id: 110, name: 'Strahlenheilkunde - Hämatologie und internistische Onkologie' },
  { id: 111, name: 'Strahlenheilkunde - Radiologie ' },
  { id: 112, name: 'Suchtmedizin ' },
  { id: 113, name: 'Thoraxchirurgie ' },
  { id: 114, name: 'Thoraxchirurgie - Intensivmedizin ' },
  { id: 115, name: 'Thoraxchirurgie - Herzchirurgie ' },
  { id: 116, name: 'Unfallchirurgie' },
  { id: 117, name: 'Urologie' },
  { id: 118, name: 'Viszeralchirurgie' },
  { id: 119, name: 'Wirbelsäulenchirurgie' },
  { id: 120, name: 'Zahn- und Kieferheilkunde - Mund- und Kieferchirurgie ' },
  { id: 121, name: 'Physiotherapie, Ergotherapie ' },
  { id: 122, name: 'Rehabilitätion' },
  { id: 123, name: 'Kopf- und Halschirurgie' },
  { id: 124, name: 'Koloproktologie' },
  { id: 125, name: 'Kinder- und Jugendmedizin' },
  { id: 126, name: 'Allergologie' }]

const cities = [
  { name: "Aachen" },
  { name: "Aalen" },
  { name: "Achern" },
  { name: "Achim" },
  { name: "Ahaus" },
  { name: "Ahlen" },
  { name: "Ahrensburg" },
  { name: "Aichach" },
  { name: "Albstadt" },
  { name: "Aldenhoven" },
  { name: "Alfter" },
  { name: "Alpen" },
  { name: "Alsdorf" },
  { name: "Altena" },
  { name: "Altenbeken" },
  { name: "Altenberge" },
  { name: "Altenburg" },
  { name: "Altenkirchen" },
  { name: "Altötting" },
  { name: "Alzey" },
  { name: "Amberg" },
  { name: "Andernach" },
  { name: "Annaberg-Buchholz" },
  { name: "Anröchte" },
  { name: "Ansbach" },
  { name: "Apolda" },
  { name: "Arnsberg" },
  { name: "Arnstadt" },
  { name: "Aschaffenburg" },
  { name: "Ascheberg" },
  { name: "Aschersleben" },
  { name: "Attendorn" },
  { name: "Augsburg" },
  { name: "Augustdorf" },
  { name: "Aurich" },
  { name: "Backnang" },
  { name: "Bad Berleburg" },
  { name: "Bad Driburg" },
  { name: "Bad Dürkheim" },
  { name: "Bad Ems" },
  { name: "Bad Fallingbostel" },
  { name: "Bad Hersfeld" },
  { name: "Bad Homburg" },
  { name: "Bad Honnef" },
  { name: "Bad Honnef am Rhein" },
  { name: "Bad Kissingen" },
  { name: "Bad Kreuznach" },
  { name: "Bad Laasphe" },
  { name: "Bad Lippspringe" },
  { name: "Bad Münstereifel" },
  { name: "Bad Nauheim" },
  { name: "Bad Neuenahr-Ahrweiler" },
  { name: "Bad Neustadt" },
  { name: "Bad Oeynhausen" },
  { name: "Bad Oldesloe" },
  { name: "Bad Reichenhall" },
  { name: "Bad Salzuflen" },
  { name: "Bad Salzungen" },
  { name: "Bad Sassendorf" },
  { name: "Bad Schwalbach" },
  { name: "Bad Segeberg" },
  { name: "Bad Tölz" },
  { name: "Bad Vilbel" },
  { name: "Bad Wünnenberg" },
  { name: "Baden-Baden" },
  { name: "Baesweiler" },
  { name: "Balingen" },
  { name: "Balve" },
  { name: "Bamberg" },
  { name: "Barntrup" },
  { name: "Barsinghausen" },
  { name: "Baunatal" },
  { name: "Bautzen" },
  { name: "Bayreuth" },
  { name: "Beckum" },
  { name: "Bedburg" },
  { name: "Bedburg-Hau" },
  { name: "Beelen" },
  { name: "Beeskow" },
  { name: "Bensheim" },
  { name: "Bergheim" },
  { name: "Bergisch Gladbach" },
  { name: "Bergkamen" },
  { name: "Bergneustadt" },
  { name: "Berlin" },
  { name: "Bernburg" },
  { name: "Bestwig" },
  { name: "Beverungen" },
  { name: "Biberach" },
  { name: "Bielefeld" },
  { name: "Bietigheim-Bissingen" },
  { name: "Billerbeck" },
  { name: "Bingen am Rhein" },
  { name: "Birkenfeld" },
  { name: "Bitburg" },
  { name: "Bitterfeld" },
  { name: "Blankenheim" },
  { name: "Blomberg" },
  { name: "Bocholt" },
  { name: "Bochum" },
  { name: "Bonn" },
  { name: "Borchen" },
  { name: "Borgentreich" },
  { name: "Borgholzhausen" },
  { name: "Borken" },
  { name: "Bornheim" },
  { name: "Bottrop" },
  { name: "Brake" },
  { name: "Brakel" },
  { name: "Bramsche" },
  { name: "Brandenburg" },
  { name: "Braunschweig" },
  { name: "Breckerfeld" },
  { name: "Bremen" },
  { name: "Bremerhaven" },
  { name: "Bretten" },
  { name: "Brilon" },
  { name: "Bruchsal" },
  { name: "Brüggen" },
  { name: "Brühl" },
  { name: "Burbach" },
  { name: "Burg" },
  { name: "Burgdorf" },
  { name: "Burscheid" },
  { name: "Butzbach" },
  { name: "Buxtehude" },
  { name: "Böblingen" },
  { name: "Bönen" },
  { name: "Bühl" },
  { name: "Bünde" },
  { name: "Büren" },
  { name: "Calw" },
  { name: "Castrop-Rauxel" },
  { name: "Celle" },
  { name: "Cham" },
  { name: "Chemnitz" },
  { name: "Cloppenburg" },
  { name: "Coburg" },
  { name: "Cochem" },
  { name: "Coesfeld" },
  { name: "Cologne" },
  { name: "Cottbus" },
  { name: "Crailsheim" },
  { name: "Cuxhaven" },
  { name: "Dachau" },
  { name: "Dahlem" },
  { name: "Darmstadt" },
  { name: "Datteln" },
  { name: "Daun" },
  { name: "Deggendorf" },
  { name: "Delbrück" },
  { name: "Delitzsch" },
  { name: "Delmenhorst" },
  { name: "Derne" },
  { name: "Dessau-Roßlau" },
  { name: "Detmold" },
  { name: "Diepholz" },
  { name: "Dietzenbach" },
  { name: "Dillingen" },
  { name: "Dingolfing" },
  { name: "Dinslaken" },
  { name: "Ditzingen" },
  { name: "Donauwörth" },
  { name: "Dormagen" },
  { name: "Dorsten" },
  { name: "Dortmund" },
  { name: "Dreieich" },
  { name: "Drensteinfurt" },
  { name: "Dresden" },
  { name: "Drolshagen" },
  { name: "Duisburg" },
  { name: "Dörentrup" },
  { name: "Dülmen" },
  { name: "Düren" },
  { name: "Düsseldorf" },
  { name: "Ebersberg" },
  { name: "Eberswalde" },
  { name: "Ehingen an der Donau" },
  { name: "Eichstätt" },
  { name: "Einbeck" },
  { name: "Eisenach" },
  { name: "Eisenberg" },
  { name: "Eitorf" },
  { name: "Elmshorn" },
  { name: "Elsdorf" },
  { name: "Emden" },
  { name: "Emmendingen" },
  { name: "Emmerich" },
  { name: "Emsdetten" },
  { name: "Engelskirchen" },
  { name: "Enger" },
  { name: "Ennepetal" },
  { name: "Ennigerloh" },
  { name: "Ense" },
  { name: "Erbach" },
  { name: "Erding" },
  { name: "Erftstadt" },
  { name: "Erfurt" },
  { name: "Erkelenz" },
  { name: "Erkrath" },
  { name: "Erlangen" },
  { name: "Erndtebrück" },
  { name: "Erwitte" },
  { name: "Eschwege" },
  { name: "Eschweiler" },
  { name: "Eslohe" },
  { name: "Espelkamp" },
  { name: "Essen" },
  { name: "Esslingen" },
  { name: "Ettlingen" },
  { name: "Euskirchen" },
  { name: "Eutin" },
  { name: "Everswinkel" },
  { name: "Extertal" },
  { name: "Falkensee" },
  { name: "Fellbach" },
  { name: "Filderstadt" },
  { name: "Finnentrop" },
  { name: "Flensburg" },
  { name: "Forchheim" },
  { name: "Forst" },
  { name: "Frankenthal" },
  { name: "Frankfurt" },
  { name: "Frankfurt (Oder)" },
  { name: "Frechen" },
  { name: "Freiberg" },
  { name: "Freiburg" },
  { name: "Freiburg im Breisgau" },
  { name: "Freising" },
  { name: "Freital" },
  { name: "Freudenberg" },
  { name: "Freudenstadt" },
  { name: "Freyung" },
  { name: "Friedberg" },
  { name: "Friedberg-Hesse" },
  { name: "Friedrichsdorf" },
  { name: "Friedrichshafen" },
  { name: "Fröndenberg" },
  { name: "Fulda" },
  { name: "Fürstenfeldbruck" },
  { name: "Fürstenwalde" },
  { name: "Fürth" },
  { name: "Gaggenau" },
  { name: "Gangelt" },
  { name: "Garbsen" },
  { name: "Garmisch-Partenkirchen" },
  { name: "Geesthacht" },
  { name: "Geilenkirchen" },
  { name: "Geislingen an der Steige" },
  { name: "Geldern" },
  { name: "Gelsenkirchen" },
  { name: "Georgsmarienhütte" },
  { name: "Gera" },
  { name: "Geretsried" },
  { name: "Germering" },
  { name: "Germersheim" },
  { name: "Gescher" },
  { name: "Geseke" },
  { name: "Gevelsberg" },
  { name: "Gießen" },
  { name: "Gifhorn" },
  { name: "Gladbeck" },
  { name: "Goch" },
  { name: "Goslar" },
  { name: "Gotha" },
  { name: "Grefrath" },
  { name: "Greifswald" },
  { name: "Greiz" },
  { name: "Greven" },
  { name: "Grevenbroich" },
  { name: "Griesheim" },
  { name: "Grimma" },
  { name: "Gronau" },
  { name: "Groß-Gerau" },
  { name: "Gummersbach" },
  { name: "Göppingen" },
  { name: "Görlitz" },
  { name: "Göttingen" },
  { name: "Günzburg" },
  { name: "Güstrow" },
  { name: "Gütersloh" },
  { name: "Haan" },
  { name: "Hagen" },
  { name: "Halberstadt" },
  { name: "Haldensleben" },
  { name: "Halle" },
  { name: "Hallenberg" },
  { name: "Haltern" },
  { name: "Halver" },
  { name: "Hamburg" },
  { name: "Hameln" },
  { name: "Hamm" },
  { name: "Hamminkeln" },
  { name: "Hanau" },
  { name: "Hannover" },
  { name: "Harsewinkel" },
  { name: "Hattingen" },
  { name: "Havixbeck" },
  { name: "Haßfurt" },
  { name: "Heek" },
  { name: "Heide" },
  { name: "Heidelberg" },
  { name: "Heiden" },
  { name: "Heidenheim" },
  { name: "Heilbad Heiligenstadt" },
  { name: "Heilbronn" },
  { name: "Heiligenhaus" },
  { name: "Heimbach" },
  { name: "Heinsberg" },
  { name: "Hellenthal" },
  { name: "Helmstedt" },
  { name: "Hemer" },
  { name: "Hennef" },
  { name: "Hennigsdorf" },
  { name: "Heppenheim" },
  { name: "Herdecke" },
  { name: "Herford" },
  { name: "Herne" },
  { name: "Herrenberg" },
  { name: "Herscheid" },
  { name: "Herten" },
  { name: "Herzberg" },
  { name: "Herzebrock-Clarholz" },
  { name: "Herzogenrath" },
  { name: "Hiddenhausen" },
  { name: "Hilchenbach" },
  { name: "Hildburghausen" },
  { name: "Hilden" },
  { name: "Hildesheim" },
  { name: "Hille" },
  { name: "Hof" },
  { name: "Hofheim" },
  { name: "Hohen Neuendorf" },
  { name: "Holzminden" },
  { name: "Holzwickede" },
  { name: "Homberg" },
  { name: "Homburg" },
  { name: "Hopsten" },
  { name: "Horb am Neckar" },
  { name: "Horn-Bad Meinberg" },
  { name: "Horstmar" },
  { name: "Hoyerswerda" },
  { name: "Husum" },
  { name: "Hörstel" },
  { name: "Hövelhof" },
  { name: "Höxter" },
  { name: "Hückelhoven" },
  { name: "Hückeswagen" },
  { name: "Hüllhorst" },
  { name: "Hünxe" },
  { name: "Hürtgenwald" },
  { name: "Hürth" },
  { name: "Ibbenbüren" },
  { name: "Idar-Oberstein" },
  { name: "Idstein" },
  { name: "Ilmenau" },
  { name: "Inden" },
  { name: "Ingelheim" },
  { name: "Ingolstadt" },
  { name: "Iserlohn" },
  { name: "Isselburg" },
  { name: "Issum" },
  { name: "Itzehoe" },
  { name: "Jena" },
  { name: "Jever" },
  { name: "Jüchen" },
  { name: "Jülich" },
  { name: "Kaarst" },
  { name: "Kaiserslautern" },
  { name: "Kalkar" },
  { name: "Kall" },
  { name: "Kalletal" },
  { name: "Kamen" },
  { name: "Kamp-Lintfort" },
  { name: "Karlsruhe" },
  { name: "Karlstadt" },
  { name: "Kassel" },
  { name: "Kaufbeuren" },
  { name: "Kehl" },
  { name: "Kelheim" },
  { name: "Kelkheim (Taunus)" },
  { name: "Kempen" },
  { name: "Kempten" },
  { name: "Kerken" },
  { name: "Kerpen" },
  { name: "Kevelaer" },
  { name: "Kiel" },
  { name: "Kierspe" },
  { name: "Kirchheim unter Teck" },
  { name: "Kirchheimbolanden" },
  { name: "Kirchhundem" },
  { name: "Kirchlengern" },
  { name: "Kitzingen" },
  { name: "Kleve" },
  { name: "Koblenz" },
  { name: "Konstanz" },
  { name: "Korbach" },
  { name: "Kornwestheim" },
  { name: "Korschenbroich" },
  { name: "Kranenburg" },
  { name: "Krefeld" },
  { name: "Kreuzau" },
  { name: "Kreuztal" },
  { name: "Kronach" },
  { name: "Kulmbach" },
  { name: "Kusel" },
  { name: "Köln" },
  { name: "Königs Wusterhausen" },
  { name: "Königsbrunn" },
  { name: "Königswinter" },
  { name: "Köthen" },
  { name: "Künzelsau" },
  { name: "Kürten" },
  { name: "Laatzen" },
  { name: "Ladbergen" },
  { name: "Laer" },
  { name: "Lage" },
  { name: "Lampertheim" },
  { name: "Landau" },
  { name: "Landsberg" },
  { name: "Landshut" },
  { name: "Langen" },
  { name: "Langenberg" },
  { name: "Langenfeld" },
  { name: "Langenhagen" },
  { name: "Langerwehe" },
  { name: "Lauf" },
  { name: "Lauterbach" },
  { name: "Leer" },
  { name: "Legden" },
  { name: "Lehrte" },
  { name: "Leichlingen" },
  { name: "Leimen" },
  { name: "Leinfelden-Echterdingen" },
  { name: "Leipzig" },
  { name: "Lemgo" },
  { name: "Lengerich" },
  { name: "Lennestadt" },
  { name: "Leonberg" },
  { name: "Leopoldshöhe" },
  { name: "Leverkusen" },
  { name: "Lichtenau" },
  { name: "Lichtenfels" },
  { name: "Lienen" },
  { name: "Limburg" },
  { name: "Lindau" },
  { name: "Lindlar" },
  { name: "Lingen" },
  { name: "Linnich" },
  { name: "Lippetal" },
  { name: "Lippstadt" },
  { name: "Lohmar" },
  { name: "Lohne" },
  { name: "Lotte" },
  { name: "Luckenwalde" },
  { name: "Ludwigsburg" },
  { name: "Ludwigsfelde" },
  { name: "Ludwigshafen" },
  { name: "Löhne" },
  { name: "Lörrach" },
  { name: "Lübbecke" },
  { name: "Lübben" },
  { name: "Lübeck" },
  { name: "Lüchow" },
  { name: "Lüdenscheid" },
  { name: "Lüdinghausen" },
  { name: "Lügde" },
  { name: "Lüneburg" },
  { name: "Lünen" },
  { name: "Magdeburg" },
  { name: "Maintal" },
  { name: "Mainz" },
  { name: "Mannheim" },
  { name: "Marburg" },
  { name: "Marienheide" },
  { name: "Marienmünster" },
  { name: "Marktoberdorf" },
  { name: "Marl" },
  { name: "Marsberg" },
  { name: "Mechernich" },
  { name: "Meckenheim" },
  { name: "Medebach" },
  { name: "Meerbusch" },
  { name: "Meinerzhagen" },
  { name: "Meiningen" },
  { name: "Meißen" },
  { name: "Melle" },
  { name: "Memmingen" },
  { name: "Menden" },
  { name: "Meppen" },
  { name: "Merseburg" },
  { name: "Merzenich" },
  { name: "Merzig" },
  { name: "Meschede" },
  { name: "Metelen" },
  { name: "Mettingen" },
  { name: "Mettmann" },
  { name: "Miesbach" },
  { name: "Miltenberg" },
  { name: "Mindelheim" },
  { name: "Minden" },
  { name: "Moers" },
  { name: "Monheim am Rhein" },
  { name: "Monschau" },
  { name: "Montabaur" },
  { name: "Morsbach" },
  { name: "Mosbach" },
  { name: "Much" },
  { name: "Munich" },
  { name: "Möhnesee" },
  { name: "Mönchengladbach" },
  { name: "Mörfelden-Walldorf" },
  { name: "Mühlacker" },
  { name: "Mühldorf" },
  { name: "Mühlhausen" },
  { name: "Mülheim" },
  { name: "Mülheim an der Ruhr" },
  { name: "München" },
  { name: "Münster" },
  { name: "Nachrodt-Wiblingwerde" },
  { name: "Naumburg" },
  { name: "Neckarsulm" },
  { name: "Netphen" },
  { name: "Nettersheim" },
  { name: "Nettetal" },
  { name: "Neu Isenburg" },
  { name: "Neu-Ulm" },
  { name: "Neubrandenburg" },
  { name: "Neuburg" },
  { name: "Neuenkirchen" },
  { name: "Neuenrade" },
  { name: "Neukirchen-Vluyn" },
  { name: "Neumarkt" },
  { name: "Neumünster" },
  { name: "Neunkirchen" },
  { name: "Neunkirchen-Seelscheid" },
  { name: "Neuruppin" },
  { name: "Neuss" },
  { name: "Neustadt" },
  { name: "Neustadt am Rübenberge" },
  { name: "Neustadt-Baden-Württemberg" },
  { name: "Neustadt-Bavaria" },
  { name: "Neustadt-Hesse" },
  { name: "Neuwied" },
  { name: "Nideggen" },
  { name: "Niederkassel" },
  { name: "Niederkrüchten" },
  { name: "Niederzier" },
  { name: "Nieheim" },
  { name: "Nienburg" },
  { name: "Norden" },
  { name: "Nordenham" },
  { name: "Norderstedt" },
  { name: "Nordhausen" },
  { name: "Nordhorn" },
  { name: "Nordkirchen" },
  { name: "Nordwalde" },
  { name: "Northeim" },
  { name: "Nottuln" },
  { name: "Nuremberg" },
  { name: "Nörvenich" },
  { name: "Nümbrecht" },
  { name: "Nürnberg" },
  { name: "Nürtingen" },
  { name: "Oberhausen" },
  { name: "Obertshausen" },
  { name: "Oberursel" },
  { name: "Ochtrup" },
  { name: "Odenthal" },
  { name: "Oelde" },
  { name: "Oer-Erkenschwick" },
  { name: "Oerlinghausen" },
  { name: "Offenbach" },
  { name: "Offenburg" },
  { name: "Olching" },
  { name: "Oldenburg" },
  { name: "Olfen" },
  { name: "Olpe" },
  { name: "Olsberg" },
  { name: "Oranienburg" },
  { name: "Osnabrück" },
  { name: "Ostbevern" },
  { name: "Osterholz-Scharmbeck" },
  { name: "Osterode" },
  { name: "Ostfildern" },
  { name: "Overath" },
  { name: "Paderborn" },
  { name: "Papenburg" },
  { name: "Parchim" },
  { name: "Passau" },
  { name: "Peine" },
  { name: "Perleberg" },
  { name: "Petershagen" },
  { name: "Pfaffenhofen" },
  { name: "Pfarrkirchen" },
  { name: "Pforzheim" },
  { name: "Pfungstadt" },
  { name: "Pinneberg" },
  { name: "Pirmasens" },
  { name: "Pirna" },
  { name: "Plauen" },
  { name: "Plettenberg" },
  { name: "Plön" },
  { name: "Porta Westfalica" },
  { name: "Potsdam" },
  { name: "Prenzlau" },
  { name: "Preußisch Oldendorf" },
  { name: "Pulheim" },
  { name: "Radebeul" },
  { name: "Radevormwald" },
  { name: "Radolfzell am Bodensee" },
  { name: "Raesfeld" },
  { name: "Rahden" },
  { name: "Rastatt" },
  { name: "Rathenow" },
  { name: "Ratingen" },
  { name: "Ratzeburg" },
  { name: "Ravensburg" },
  { name: "Recke" },
  { name: "Recklinghausen" },
  { name: "Rees" },
  { name: "Regen" },
  { name: "Regensburg" },
  { name: "Reichshof" },
  { name: "Reinbek" },
  { name: "Reken" },
  { name: "Remscheid" },
  { name: "Rendsburg" },
  { name: "Reutlingen" },
  { name: "Rheda-Wiedenbrück" },
  { name: "Rhede" },
  { name: "Rheinbach" },
  { name: "Rheinberg" },
  { name: "Rheine" },
  { name: "Rheinfelden (Baden)" },
  { name: "Rheurdt" },
  { name: "Riesa" },
  { name: "Rietberg" },
  { name: "Rinteln" },
  { name: "Rodgau" },
  { name: "Roetgen" },
  { name: "Rommerskirchen" },
  { name: "Rosendahl" },
  { name: "Rosenheim" },
  { name: "Rostock" },
  { name: "Rotenburg" },
  { name: "Roth" },
  { name: "Rottweil" },
  { name: "Rudolstadt" },
  { name: "Ruppichteroth" },
  { name: "Rödinghausen" },
  { name: "Rösrath" },
  { name: "Rüthen" },
  { name: "Saalfeld" },
  { name: "Saarbrücken" },
  { name: "Saarlouis" },
  { name: "Saerbeck" },
  { name: "Salzgitter" },
  { name: "Salzkotten" },
  { name: "Salzwedel" },
  { name: "Sangerhausen" },
  { name: "Sankt Augustin" },
  { name: "Sankt Ingbert" },
  { name: "Sankt Wendel" },
  { name: "Sassenberg" },
  { name: "Schalksmühle" },
  { name: "Schermbeck" },
  { name: "Schieder-Schwalenberg" },
  { name: "Schlangen" },
  { name: "Schleiden" },
  { name: "Schleiz" },
  { name: "Schleswig" },
  { name: "Schloß Holte-Stukenbrock" },
  { name: "Schmallenberg" },
  { name: "Schorndorf" },
  { name: "Schwabach" },
  { name: "Schwalmtal" },
  { name: "Schwandorf" },
  { name: "Schwedt (Oder)" },
  { name: "Schweinfurt" },
  { name: "Schwelm" },
  { name: "Schwerin" },
  { name: "Schwerte" },
  { name: "Schwäbisch Gmünd" },
  { name: "Schwäbisch Hall" },
  { name: "Schönebeck" },
  { name: "Schöppingen" },
  { name: "Seelow" },
  { name: "Seelze" },
  { name: "Selfkant" },
  { name: "Selm" },
  { name: "Senden" },
  { name: "Sendenhorst" },
  { name: "Senftenberg" },
  { name: "Siegburg" },
  { name: "Siegen" },
  { name: "Sigmaringen" },
  { name: "Simmerath" },
  { name: "Simmern" },
  { name: "Sindelfingen" },
  { name: "Sinsheim" },
  { name: "Soest" },
  { name: "Solingen" },
  { name: "Sondershausen" },
  { name: "Sonneberg" },
  { name: "Sonsbeck" },
  { name: "Sonthofen" },
  { name: "Spenge" },
  { name: "Speyer" },
  { name: "Springe" },
  { name: "Sprockhövel" },
  { name: "Stade" },
  { name: "Stadthagen" },
  { name: "Stadtlohn" },
  { name: "Starnberg" },
  { name: "Staßfurt" },
  { name: "Steinfurt" },
  { name: "Steinhagen" },
  { name: "Steinheim" },
  { name: "Steinheim am Main" },
  { name: "Stemwede" },
  { name: "Stendal" },
  { name: "Stolberg" },
  { name: "Straelen" },
  { name: "Stralsund" },
  { name: "Straubing" },
  { name: "Strausberg" },
  { name: "Stuttgart" },
  { name: "Suhl" },
  { name: "Sundern" },
  { name: "Swisttal" },
  { name: "Sömmerda" },
  { name: "Südlohn" },
  { name: "Tauberbischofsheim" },
  { name: "Taunusstein" },
  { name: "Tecklenburg" },
  { name: "Telgte" },
  { name: "Teltow" },
  { name: "Tirschenreuth" },
  { name: "Titz" },
  { name: "Torgau" },
  { name: "Traunstein" },
  { name: "Trier" },
  { name: "Troisdorf" },
  { name: "Tuttlingen" },
  { name: "Tönisvorst" },
  { name: "Tübingen" },
  { name: "Uedem" },
  { name: "Uelzen" },
  { name: "Ulm" },
  { name: "Unna" },
  { name: "Unterschleißheim" },
  { name: "Vaihingen an der Enz" },
  { name: "Vechta" },
  { name: "Velbert" },
  { name: "Velen" },
  { name: "Verden" },
  { name: "Verl" },
  { name: "Versmold" },
  { name: "Vettweiß" },
  { name: "Viernheim" },
  { name: "Viersen" },
  { name: "Villingen-Schwenningen" },
  { name: "Vlotho" },
  { name: "Voerde" },
  { name: "Vreden" },
  { name: "Völklingen" },
  { name: "Wachtberg" },
  { name: "Wachtendonk" },
  { name: "Wadersloh" },
  { name: "Waiblingen" },
  { name: "Waldbröl" },
  { name: "Waldfeucht" },
  { name: "Waldshut-Tiengen" },
  { name: "Waltrop" },
  { name: "Wangen im Allgäu" },
  { name: "Warburg" },
  { name: "Warendorf" },
  { name: "Warstein" },
  { name: "Wassenberg" },
  { name: "Wedel" },
  { name: "Weeze" },
  { name: "Wegberg" },
  { name: "Weiden" },
  { name: "Weil am Rhein" },
  { name: "Weilerswist" },
  { name: "Weilheim" },
  { name: "Weimar" },
  { name: "Weingarten" },
  { name: "Weinheim" },
  { name: "Weiterstadt" },
  { name: "Weißenburg" },
  { name: "Weißenfels" },
  { name: "Welver" },
  { name: "Wenden" },
  { name: "Werdohl" },
  { name: "Werl" },
  { name: "Wermelskirchen" },
  { name: "Werne" },
  { name: "Wernigerode" },
  { name: "Werther" },
  { name: "Wesel" },
  { name: "Wesseling" },
  { name: "Westerkappeln" },
  { name: "Westerstede" },
  { name: "Wetter" },
  { name: "Wetter (Ruhr)" },
  { name: "Wettringen" },
  { name: "Wetzlar" },
  { name: "Wickede" },
  { name: "Wiehl" },
  { name: "Wiesbaden" },
  { name: "Wiesloch" },
  { name: "Wilhelmshaven" },
  { name: "Willebadessen" },
  { name: "Willich" },
  { name: "Wilnsdorf" },
  { name: "Windeck" },
  { name: "Winnenden" },
  { name: "Winsen" },
  { name: "Winterberg" },
  { name: "Wipperfürth" },
  { name: "Wismar" },
  { name: "Witten" },
  { name: "Wittenberg" },
  { name: "Wittlich" },
  { name: "Wittmund" },
  { name: "Wolfenbüttel" },
  { name: "Wolfsburg" },
  { name: "Worms" },
  { name: "Wunsiedel" },
  { name: "Wunstorf" },
  { name: "Wuppertal" },
  { name: "Wülfrath" },
  { name: "Würselen" },
  { name: "Würzburg" },
  { name: "Xanten" },
  { name: "Zeitz" },
  { name: "Zirndorf" },
  { name: "Zittau" },
  { name: "Zweibrücken" },
  { name: "Zwickau" },
  { name: "Zülpich" },
  { name: "Übach-Palenberg" }]
</script>
