import { useStorageAsync } from '@vueuse/core'

const state = reactive({
  /**
   *
   * For <ClinicForm />
   *
   */
  clinic_form: {
    id: null,
    name: null,
    partnership: null,
    department: null,
    address: null,
    leader: null,
    medching_contact: null,
    website: null,
    phone: null,
    email: null,
    beds: null,
    patients: null,
    employees: null,
    education: null,
    about: null,
    specials: null,
    image: null,
    specializations: [],
    specialization_to_edit: null,
    submitted: null,
  },
  clinics: useStorageAsync('clinics', []), // when they send
  verified_clinics: useStorageAsync('verified_clinics', []), // which are verified by Appromed in the SlideOver
  docs: useStorageAsync('docs', []), // when they register through the DocForm
  vacancies: useStorageAsync('vacancies', []),
  // global loading indicator
  loading: useStorageAsync('loading', false),
  // i18n self made
  active_locale: useStorage('active_locale', 'de'),
  // actual locale data
  locales: useStorage('locales', {}),
  activator: useStorageAsync('activator', false),
  //accounts
  admin: useStorageAsync('admin', {}), // logged in admin
  user_doctor: useStorageAsync('user_doctor', {}),
  user_clinic: useStorageAsync('user_clinic', {}),
  // search results
  hospitals: useStorageAsync('hospitals', undefined),
  // search history
  past_searches: useStorageAsync('past_searches', []),
  // max_stars
  max_stars: useStorageAsync('max_stars', 5),
  // available specialiozations for doctors
  specializations: useStorageAsync('specializations', [
    { id: 1, name: "Facharzt für Allgemeinmedizin" },
    { id: 2, name: "Facharzt für Anästhesiologie" },
    { id: 3, name: "Facharzt für Anatomie" },
    { id: 4, name: "Facharzt für Arbeitsmedizin" },
    { id: 5, name: "Facharzt für Augenheilkunde" },
    { id: 6, name: "Facharzt für Biochemie" },
    { id: 7, name: "Facharzt für Allgemeine Chirurgie" },
    { id: 8, name: "Facharzt für Gefäßchirurgie" },
    { id: 9, name: "Facharzt für Herzchirurgie" },
    { id: 10, name: "Facharzt für Kinderchirurgie" },
    { id: 11, name: "Facharzt für Orthopädie und Unfallchirurgie" },
    { id: 12, name: "Facharzt für Plastische und Ästhetische Chirurgie" },
    { id: 13, name: "Facharzt für Thoraxchirurgie" },
    { id: 14, name: "Facharzt für Visceralchirurgie" },
    { id: 15, name: "Facharzt für Frauenheilkunde und Geburtshilfe" },
    { id: 16, name: "Facharzt für Frauenheilkunde und Geburtshilfe, Schwerpunkt Gynäkologische Endokrinologie und Reproduktionsmedizin" },
    { id: 17, name: "Facharzt für Frauenheilkunde und Geburtshilfe, Schwerpunkt Gynäkologische Onkologie" },
    { id: 18, name: "Facharzt für Frauenheilkunde und Geburtshilfe, Schwerpunkt Spezielle Geburtshilfe und Perinatalmedizin" },
    { id: 19, name: "Facharzt für Hals-Nasen-Ohrenheilkunde" },
    { id: 20, name: "Facharzt für Sprach-, Stimm- und kindliche Hörstörungen" },
    { id: 21, name: "Facharzt für Haut- und Geschlechtskrankheiten" },
    { id: 22, name: "Facharzt für Humangenetik" },
    { id: 23, name: "Facharzt für Hygiene und Umweltmedizin" },
    { id: 24, name: "Facharzt für Innere und Allgemeinmedizin (Hausarzt)" },
    { id: 25, name: "Facharzt für Innere Medizin" },
    { id: 26, name: "Facharzt für Innere Medizin und Angiologie" },
    { id: 27, name: "Facharzt für Innere Medizin und Endokrinologie und Diabetologie" },
    { id: 28, name: "Facharzt für Innere Medizin und Gastroenterologie" },
    { id: 29, name: "Facharzt für Innere Medizin und Hämatologie und Onkologie" },
    { id: 30, name: "Facharzt für Innere Medizin und Kardiologie" },
    { id: 31, name: "Facharzt für Innere Medizin und Nephrologie" },
    { id: 32, name: "Facharzt für Innere Medizin und Pneumologie" },
    { id: 33, name: "Facharzt für Innere Medizin und Rheumatologie" },
    { id: 34, name: "Facharzt für Gebiet Kinder- und Jugendmedizin" },
    { id: 35, name: "Facharzt für Gebiet Kinder- und Jugendmedizin, Schwerpunkt Kinder-Hämatologie und – Onkologie" },
    { id: 36, name: "Facharzt für Gebiet Kinder- und Jugendmedizin, Schwerpunkt Kinder-Kardiologie" },
    { id: 37, name: "Facharzt für Gebiet Kinder- und Jugendmedizin, Schwerpunkt Neonatologie" },
    { id: 38, name: "Facharzt für Gebiet Kinder- und Jugendmedizin, Schwerpunkt Neuropädiatrie" },
    { id: 39, name: "Facharzt für Kinder- und Jugendpsychiatrie und -psychotherapie" },
    { id: 40, name: "Facharzt für Laboratoriumsmedizin" },
    { id: 41, name: "Facharzt für Mikrobiologie, Virologie und Infektionsepidemiologie" },
    { id: 42, name: "Facharzt für Mund-Kiefer-Gesichtschirurgie" },
    { id: 43, name: "Facharzt für Neurochirurgie" },
    { id: 44, name: "Facharzt für Neurologie" },
    { id: 45, name: "Facharzt für Nuklearmedizin" },
    { id: 46, name: "Facharzt für Öffentliches Gesundheitswesen" },
    { id: 47, name: "Facharzt für Neuropathologie" },
    { id: 48, name: "Facharzt für Pathologie" },
    { id: 49, name: "Facharzt für Klinische Pharmakologie" },
    { id: 50, name: "Facharzt für Pharmakologie und Toxikologie" },
    { id: 51, name: "Facharzt für Physikalische und Rehabilitative Medizin" },
    { id: 52, name: "Facharzt für Physiologie" },
    { id: 53, name: "Facharzt für Psychiatrie und Psychotherapie" },
    { id: 54, name: "Facharzt für Psychiatrie und Psychotherapie, Schwerpunkt Forensische Psychiatrie" },
    { id: 55, name: "Facharzt für Psychosomatische Medizin und Psychotherapie" },
    { id: 56, name: "Facharzt für Radiologie" },
    { id: 57, name: "Facharzt für Radiologie, Schwerpunkt Kinderradiologie" },
    { id: 58, name: "Facharzt für Radiologie, Schwerpunkt Neuroradiologie" },
    { id: 59, name: "Facharzt für Rechtsmedizin" },
    { id: 60, name: "Facharzt für Strahlentherapie" },
    { id: 61, name: "Facharzt für Transfusionsmedizin" },
    { id: 62, name: "Facharzt für Urologie" },
  ]),
  additional_specializations: useStorageAsync('additional_specializations', [
    { id: 1, name: "Ärztliches Qualitätsmanagement" },
    { id: 2, name: "Akupunktur" },
    { id: 3, name: "Allergologie" },
    { id: 4, name: "Andrologie" },
    { id: 5, name: "Balneologie und Medizinische Klimatologie" },
    { id: 6, name: "Betriebsmedizin" },
    { id: 7, name: "Dermatopathologie" },
    { id: 8, name: "Diabetologie" },
    { id: 9, name: "Ernährungsmedizin" },
    { id: 10, name: "Flugmedizin" },
    { id: 11, name: "Geriatrie" },
    { id: 12, name: "Gynäkologische Exfoliativ-Zytologie" },
    { id: 13, name: "Hämostaseologie" },
    { id: 14, name: "Handchirurgie" },
    { id: 15, name: "Homöopathie" },
    { id: 16, name: "Immunologie" },
    { id: 17, name: "Infektiologie" },
    { id: 18, name: "Intensivmedizin" },
    { id: 19, name: "Kardiale Magnetresonanztomographie" },
    { id: 20, name: "Kinder- und Jugend-Endokrinologie und -Diabetologie" },
    { id: 21, name: "Kinder- und Jugend-Gastroenterologie" },
    { id: 22, name: "Kinder- und Jugend-Nephrologie" },
    { id: 23, name: "Kinder- und Jugend-Orthopädie" },
    { id: 24, name: "Kinder- und Jugend-Pneumologie" },
    { id: 25, name: "Kinder- und Jugend-Rheumatologie" },
    { id: 26, name: "Klinische Akut- und Notfallmedizin" },
    { id: 27, name: "Krankenhaushygiene" },
    { id: 28, name: "Magnetresonanztomographie" },
    { id: 29, name: "Manuelle Medizin" },
    { id: 30, name: "Medikamentöse Tumortherapie" },
    { id: 31, name: "Medizinische Informatik" },
    { id: 32, name: "Naturheilverfahren" },
    { id: 33, name: "Notfallmedizin" },
    { id: 34, name: "Nuklearmedizinische Diagnostik für Radiologen" },
    { id: 35, name: "Orthopädische Rheumatologie" },
    { id: 36, name: "Palliativmedizin" },
    { id: 37, name: "Phlebologie" },
    { id: 38, name: "Physikalische Therapie" },
    { id: 39, name: "Plastische und Ästhetische Operationen" },
    { id: 40, name: "Proktologie" },
    { id: 41, name: "Psychoanalyse" },
    { id: 42, name: "Psychotherapie" },
    { id: 43, name: "Rehabilitationswesen" },
    { id: 44, name: "Röntgendiagnostik für Nuklearmediziner" },
    { id: 45, name: "Schlafmedizin" },
    { id: 46, name: "Sexualmedizin" },
    { id: 47, name: "Sozialmedizin" },
    { id: 48, name: "Spezielle Kardiologie für Erwachsene mit angeborenem Herzfehler" },
    { id: 49, name: "Spezielle Kinder- und Jugend-Urologie" },
    { id: 50, name: "Spezielle Orthopädische Chirurgie" },
    { id: 51, name: "Spezielle Schmerztherapie" },
    { id: 52, name: "Spezielle Unfallchirurgie" },
    { id: 53, name: "Spezielle Viszeralchirurgie" },
    { id: 54, name: "Sportmedizin" },
    { id: 55, name: "Suchtmedizinische Grundversorgung" },
    { id: 56, name: "Transplantationsmedizin" },
    { id: 57, name: "Tropenmedizin" },
  ]),
  // All German cities
  cities: useStorageAsync('cities', [
    { id: 1, name: "Aachen" },
    { id: 2, name: "Aalen" },
    { id: 3, name: "Achern" },
    { id: 4, name: "Achim" },
    { id: 5, name: "Ahaus" },
    { id: 6, name: "Ahlen" },
    { id: 7, name: "Ahrensburg" },
    { id: 8, name: "Aichach" },
    { id: 9, name: "Albstadt" },
    { id: 10, name: "Aldenhoven" },
    { id: 11, name: "Alfter" },
    { id: 12, name: "Alpen" },
    { id: 13, name: "Alsdorf" },
    { id: 14, name: "Altena" },
    { id: 15, name: "Altenbeken" },
    { id: 16, name: "Altenberge" },
    { id: 17, name: "Altenburg" },
    { id: 18, name: "Altenkirchen" },
    { id: 19, name: "Altötting" },
    { id: 20, name: "Alzey" },
    { id: 21, name: "Amberg" },
    { id: 22, name: "Andernach" },
    { id: 23, name: "Annaberg-Buchholz" },
    { id: 24, name: "Anröchte" },
    { id: 25, name: "Ansbach" },
    { id: 26, name: "Apolda" },
    { id: 27, name: "Arnsberg" },
    { id: 28, name: "Arnstadt" },
    { id: 29, name: "Aschaffenburg" },
    { id: 30, name: "Ascheberg" },
    { id: 31, name: "Aschersleben" },
    { id: 32, name: "Attendorn" },
    { id: 33, name: "Augsburg" },
    { id: 34, name: "Augustdorf" },
    { id: 35, name: "Aurich" },
    { id: 36, name: "Backnang" },
    { id: 37, name: "Bad Berleburg" },
    { id: 38, name: "Bad Driburg" },
    { id: 39, name: "Bad Dürkheim" },
    { id: 40, name: "Bad Ems" },
    { id: 41, name: "Bad Fallingbostel" },
    { id: 42, name: "Bad Hersfeld" },
    { id: 43, name: "Bad Homburg" },
    { id: 44, name: "Bad Honnef" },
    { id: 45, name: "Bad Honnef am Rhein" },
    { id: 46, name: "Bad Kissingen" },
    { id: 47, name: "Bad Kreuznach" },
    { id: 48, name: "Bad Laasphe" },
    { id: 49, name: "Bad Lippspringe" },
    { id: 50, name: "Bad Münstereifel" },
    { id: 51, name: "Bad Nauheim" },
    { id: 52, name: "Bad Neuenahr-Ahrweiler" },
    { id: 53, name: "Bad Neustadt" },
    { id: 54, name: "Bad Oeynhausen" },
    { id: 55, name: "Bad Oldesloe" },
    { id: 56, name: "Bad Reichenhall" },
    { id: 57, name: "Bad Salzuflen" },
    { id: 58, name: "Bad Salzungen" },
    { id: 59, name: "Bad Sassendorf" },
    { id: 60, name: "Bad Schwalbach" },
    { id: 61, name: "Bad Segeberg" },
    { id: 62, name: "Bad Tölz" },
    { id: 63, name: "Bad Vilbel" },
    { id: 64, name: "Bad Wünnenberg" },
    { id: 65, name: "Baden-Baden" },
    { id: 66, name: "Baesweiler" },
    { id: 67, name: "Balingen" },
    { id: 68, name: "Balve" },
    { id: 69, name: "Bamberg" },
    { id: 70, name: "Barntrup" },
    { id: 71, name: "Barsinghausen" },
    { id: 72, name: "Baunatal" },
    { id: 73, name: "Bautzen" },
    { id: 74, name: "Bayreuth" },
    { id: 75, name: "Beckum" },
    { id: 76, name: "Bedburg" },
    { id: 77, name: "Bedburg-Hau" },
    { id: 78, name: "Beelen" },
    { id: 79, name: "Beeskow" },
    { id: 80, name: "Bensheim" },
    { id: 81, name: "Bergheim" },
    { id: 82, name: "Bergisch Gladbach" },
    { id: 83, name: "Bergkamen" },
    { id: 84, name: "Bergneustadt" },
    { id: 85, name: "Berlin" },
    { id: 86, name: "Bernburg" },
    { id: 87, name: "Bestwig" },
    { id: 88, name: "Beverungen" },
    { id: 89, name: "Biberach" },
    { id: 90, name: "Bielefeld" },
    { id: 91, name: "Bietigheim-Bissingen" },
    { id: 92, name: "Billerbeck" },
    { id: 93, name: "Bingen am Rhein" },
    { id: 94, name: "Birkenfeld" },
    { id: 95, name: "Bitburg" },
    { id: 96, name: "Bitterfeld" },
    { id: 97, name: "Blankenheim" },
    { id: 98, name: "Blomberg" },
    { id: 99, name: "Bocholt" },
    { id: 100, name: "Bochum" },
    { id: 101, name: "Bonn" },
    { id: 102, name: "Borchen" },
    { id: 103, name: "Borgentreich" },
    { id: 104, name: "Borgholzhausen" },
    { id: 105, name: "Borken" },
    { id: 106, name: "Bornheim" },
    { id: 107, name: "Bottrop" },
    { id: 108, name: "Brake" },
    { id: 109, name: "Brakel" },
    { id: 110, name: "Bramsche" },
    { id: 111, name: "Brandenburg" },
    { id: 112, name: "Braunschweig" },
    { id: 113, name: "Breckerfeld" },
    { id: 114, name: "Bremen" },
    { id: 115, name: "Bremerhaven" },
    { id: 116, name: "Bretten" },
    { id: 117, name: "Brilon" },
    { id: 118, name: "Bruchsal" },
    { id: 119, name: "Brüggen" },
    { id: 120, name: "Brühl" },
    { id: 121, name: "Burbach" },
    { id: 122, name: "Burg" },
    { id: 123, name: "Burgdorf" },
    { id: 124, name: "Burscheid" },
    { id: 125, name: "Butzbach" },
    { id: 126, name: "Buxtehude" },
    { id: 127, name: "Böblingen" },
    { id: 128, name: "Bönen" },
    { id: 129, name: "Bühl" },
    { id: 130, name: "Bünde" },
    { id: 131, name: "Büren" },
    { id: 132, name: "Calw" },
    { id: 133, name: "Castrop-Rauxel" },
    { id: 134, name: "Celle" },
    { id: 135, name: "Cham" },
    { id: 136, name: "Chemnitz" },
    { id: 137, name: "Cloppenburg" },
    { id: 138, name: "Coburg" },
    { id: 139, name: "Cochem" },
    { id: 140, name: "Coesfeld" },
    { id: 141, name: "Cologne" },
    { id: 142, name: "Cottbus" },
    { id: 143, name: "Crailsheim" },
    { id: 144, name: "Cuxhaven" },
    { id: 145, name: "Dachau" },
    { id: 146, name: "Dahlem" },
    { id: 147, name: "Darmstadt" },
    { id: 148, name: "Datteln" },
    { id: 149, name: "Daun" },
    { id: 150, name: "Deggendorf" },
    { id: 151, name: "Delbrück" },
    { id: 152, name: "Delitzsch" },
    { id: 153, name: "Delmenhorst" },
    { id: 154, name: "Derne" },
    { id: 155, name: "Dessau-Roßlau" },
    { id: 156, name: "Detmold" },
    { id: 157, name: "Diepholz" },
    { id: 158, name: "Dietzenbach" },
    { id: 159, name: "Dillingen" },
    { id: 160, name: "Dingolfing" },
    { id: 161, name: "Dinslaken" },
    { id: 162, name: "Ditzingen" },
    { id: 163, name: "Donauwörth" },
    { id: 164, name: "Dormagen" },
    { id: 165, name: "Dorsten" },
    { id: 166, name: "Dortmund" },
    { id: 167, name: "Dreieich" },
    { id: 168, name: "Drensteinfurt" },
    { id: 169, name: "Dresden" },
    { id: 170, name: "Drolshagen" },
    { id: 171, name: "Duisburg" },
    { id: 172, name: "Dörentrup" },
    { id: 173, name: "Dülmen" },
    { id: 174, name: "Düren" },
    { id: 175, name: "Düsseldorf" },
    { id: 176, name: "Ebersberg" },
    { id: 177, name: "Eberswalde" },
    { id: 178, name: "Ehingen an der Donau" },
    { id: 179, name: "Eichstätt" },
    { id: 180, name: "Einbeck" },
    { id: 181, name: "Eisenach" },
    { id: 182, name: "Eisenberg" },
    { id: 183, name: "Eitorf" },
    { id: 184, name: "Elmshorn" },
    { id: 185, name: "Elsdorf" },
    { id: 186, name: "Emden" },
    { id: 187, name: "Emmendingen" },
    { id: 188, name: "Emmerich" },
    { id: 189, name: "Emsdetten" },
    { id: 190, name: "Engelskirchen" },
    { id: 191, name: "Enger" },
    { id: 192, name: "Ennepetal" },
    { id: 193, name: "Ennigerloh" },
    { id: 194, name: "Ense" },
    { id: 195, name: "Erbach" },
    { id: 196, name: "Erding" },
    { id: 197, name: "Erftstadt" },
    { id: 198, name: "Erfurt" },
    { id: 199, name: "Erkelenz" },
    { id: 200, name: "Erkrath" },
    { id: 201, name: "Erlangen" },
    { id: 202, name: "Erndtebrück" },
    { id: 203, name: "Erwitte" },
    { id: 204, name: "Eschwege" },
    { id: 205, name: "Eschweiler" },
    { id: 206, name: "Eslohe" },
    { id: 207, name: "Espelkamp" },
    { id: 208, name: "Essen" },
    { id: 209, name: "Esslingen" },
    { id: 210, name: "Ettlingen" },
    { id: 211, name: "Euskirchen" },
    { id: 212, name: "Eutin" },
    { id: 213, name: "Everswinkel" },
    { id: 214, name: "Extertal" },
    { id: 215, name: "Falkensee" },
    { id: 216, name: "Fellbach" },
    { id: 217, name: "Filderstadt" },
    { id: 218, name: "Finnentrop" },
    { id: 219, name: "Flensburg" },
    { id: 220, name: "Forchheim" },
    { id: 221, name: "Forst" },
    { id: 222, name: "Frankenthal" },
    { id: 223, name: "Frankfurt" },
    { id: 224, name: "Frankfurt (Oder)" },
    { id: 225, name: "Frechen" },
    { id: 226, name: "Freiberg" },
    { id: 227, name: "Freiburg" },
    { id: 228, name: "Freiburg im Breisgau" },
    { id: 229, name: "Freising" },
    { id: 230, name: "Freital" },
    { id: 231, name: "Freudenberg" },
    { id: 232, name: "Freudenstadt" },
    { id: 233, name: "Freyung" },
    { id: 234, name: "Friedberg" },
    { id: 235, name: "Friedberg-Hesse" },
    { id: 236, name: "Friedrichsdorf" },
    { id: 237, name: "Friedrichshafen" },
    { id: 238, name: "Fröndenberg" },
    { id: 239, name: "Fulda" },
    { id: 240, name: "Fürstenfeldbruck" },
    { id: 241, name: "Fürstenwalde" },
    { id: 242, name: "Fürth" },
    { id: 243, name: "Gaggenau" },
    { id: 244, name: "Gangelt" },
    { id: 245, name: "Garbsen" },
    { id: 246, name: "Garmisch-Partenkirchen" },
    { id: 247, name: "Geesthacht" },
    { id: 248, name: "Geilenkirchen" },
    { id: 249, name: "Geislingen an der Steige" },
    { id: 250, name: "Geldern" },
    { id: 251, name: "Gelsenkirchen" },
    { id: 252, name: "Georgsmarienhütte" },
    { id: 253, name: "Gera" },
    { id: 254, name: "Geretsried" },
    { id: 255, name: "Germering" },
    { id: 256, name: "Germersheim" },
    { id: 257, name: "Gescher" },
    { id: 258, name: "Geseke" },
    { id: 259, name: "Gevelsberg" },
    { id: 260, name: "Gießen" },
    { id: 261, name: "Gifhorn" },
    { id: 262, name: "Gladbeck" },
    { id: 263, name: "Goch" },
    { id: 264, name: "Goslar" },
    { id: 265, name: "Gotha" },
    { id: 266, name: "Grefrath" },
    { id: 267, name: "Greifswald" },
    { id: 268, name: "Greiz" },
    { id: 269, name: "Greven" },
    { id: 270, name: "Grevenbroich" },
    { id: 271, name: "Griesheim" },
    { id: 272, name: "Grimma" },
    { id: 273, name: "Gronau" },
    { id: 274, name: "Groß-Gerau" },
    { id: 275, name: "Gummersbach" },
    { id: 276, name: "Göppingen" },
    { id: 277, name: "Görlitz" },
    { id: 278, name: "Göttingen" },
    { id: 279, name: "Günzburg" },
    { id: 280, name: "Güstrow" },
    { id: 281, name: "Gütersloh" },
    { id: 282, name: "Haan" },
    { id: 283, name: "Hagen" },
    { id: 284, name: "Halberstadt" },
    { id: 285, name: "Haldensleben" },
    { id: 286, name: "Halle" },
    { id: 287, name: "Hallenberg" },
    { id: 288, name: "Haltern" },
    { id: 289, name: "Halver" },
    { id: 290, name: "Hamburg" },
    { id: 291, name: "Hameln" },
    { id: 292, name: "Hamm" },
    { id: 293, name: "Hamminkeln" },
    { id: 294, name: "Hanau" },
    { id: 295, name: "Hannover" },
    { id: 296, name: "Harsewinkel" },
    { id: 297, name: "Hattingen" },
    { id: 298, name: "Havixbeck" },
    { id: 299, name: "Haßfurt" },
    { id: 300, name: "Heek" },
    { id: 301, name: "Heide" },
    { id: 302, name: "Heidelberg" },
    { id: 303, name: "Heiden" },
    { id: 304, name: "Heidenheim" },
    { id: 305, name: "Heilbad Heiligenstadt" },
    { id: 306, name: "Heilbronn" },
    { id: 307, name: "Heiligenhaus" },
    { id: 308, name: "Heimbach" },
    { id: 309, name: "Heinsberg" },
    { id: 310, name: "Hellenthal" },
    { id: 311, name: "Helmstedt" },
    { id: 312, name: "Hemer" },
    { id: 313, name: "Hennef" },
    { id: 314, name: "Hennigsdorf" },
    { id: 315, name: "Heppenheim" },
    { id: 316, name: "Herdecke" },
    { id: 317, name: "Herford" },
    { id: 318, name: "Herne" },
    { id: 319, name: "Herrenberg" },
    { id: 320, name: "Herscheid" },
    { id: 321, name: "Herten" },
    { id: 322, name: "Herzberg" },
    { id: 323, name: "Herzebrock-Clarholz" },
    { id: 324, name: "Herzogenrath" },
    { id: 325, name: "Hiddenhausen" },
    { id: 326, name: "Hilchenbach" },
    { id: 327, name: "Hildburghausen" },
    { id: 328, name: "Hilden" },
    { id: 329, name: "Hildesheim" },
    { id: 330, name: "Hille" },
    { id: 331, name: "Hof" },
    { id: 332, name: "Hofheim" },
    { id: 333, name: "Hohen Neuendorf" },
    { id: 334, name: "Holzminden" },
    { id: 335, name: "Holzwickede" },
    { id: 336, name: "Homberg" },
    { id: 337, name: "Homburg" },
    { id: 338, name: "Hopsten" },
    { id: 339, name: "Horb am Neckar" },
    { id: 340, name: "Horn-Bad Meinberg" },
    { id: 341, name: "Horstmar" },
    { id: 342, name: "Hoyerswerda" },
    { id: 343, name: "Husum" },
    { id: 344, name: "Hörstel" },
    { id: 345, name: "Hövelhof" },
    { id: 346, name: "Höxter" },
    { id: 347, name: "Hückelhoven" },
    { id: 348, name: "Hückeswagen" },
    { id: 349, name: "Hüllhorst" },
    { id: 350, name: "Hünxe" },
    { id: 351, name: "Hürtgenwald" },
    { id: 352, name: "Hürth" },
    { id: 353, name: "Ibbenbüren" },
    { id: 354, name: "Idar-Oberstein" },
    { id: 355, name: "Idstein" },
    { id: 356, name: "Ilmenau" },
    { id: 357, name: "Inden" },
    { id: 358, name: "Ingelheim" },
    { id: 359, name: "Ingolstadt" },
    { id: 360, name: "Iserlohn" },
    { id: 361, name: "Isselburg" },
    { id: 362, name: "Issum" },
    { id: 363, name: "Itzehoe" },
    { id: 364, name: "Jena" },
    { id: 365, name: "Jever" },
    { id: 366, name: "Jüchen" },
    { id: 367, name: "Jülich" },
    { id: 368, name: "Kaarst" },
    { id: 369, name: "Kaiserslautern" },
    { id: 370, name: "Kalkar" },
    { id: 371, name: "Kall" },
    { id: 372, name: "Kalletal" },
    { id: 373, name: "Kamen" },
    { id: 374, name: "Kamp-Lintfort" },
    { id: 375, name: "Karlsruhe" },
    { id: 376, name: "Karlstadt" },
    { id: 377, name: "Kassel" },
    { id: 378, name: "Kaufbeuren" },
    { id: 379, name: "Kehl" },
    { id: 380, name: "Kelheim" },
    { id: 381, name: "Kelkheim (Taunus)" },
    { id: 382, name: "Kempen" },
    { id: 383, name: "Kempten" },
    { id: 384, name: "Kerken" },
    { id: 385, name: "Kerpen" },
    { id: 386, name: "Kevelaer" },
    { id: 387, name: "Kiel" },
    { id: 388, name: "Kierspe" },
    { id: 389, name: "Kirchheim unter Teck" },
    { id: 390, name: "Kirchheimbolanden" },
    { id: 391, name: "Kirchhundem" },
    { id: 392, name: "Kirchlengern" },
    { id: 393, name: "Kitzingen" },
    { id: 394, name: "Kleve" },
    { id: 395, name: "Koblenz" },
    { id: 396, name: "Konstanz" },
    { id: 397, name: "Korbach" },
    { id: 398, name: "Kornwestheim" },
    { id: 399, name: "Korschenbroich" },
    { id: 400, name: "Kranenburg" },
    { id: 401, name: "Krefeld" },
    { id: 402, name: "Kreuzau" },
    { id: 403, name: "Kreuztal" },
    { id: 404, name: "Kronach" },
    { id: 405, name: "Kulmbach" },
    { id: 406, name: "Kusel" },
    { id: 407, name: "Köln" },
    { id: 408, name: "Königs Wusterhausen" },
    { id: 409, name: "Königsbrunn" },
    { id: 410, name: "Königswinter" },
    { id: 411, name: "Köthen" },
    { id: 412, name: "Künzelsau" },
    { id: 413, name: "Kürten" },
    { id: 414, name: "Laatzen" },
    { id: 415, name: "Ladbergen" },
    { id: 416, name: "Laer" },
    { id: 417, name: "Lage" },
    { id: 418, name: "Lampertheim" },
    { id: 419, name: "Landau" },
    { id: 420, name: "Landsberg" },
    { id: 421, name: "Landshut" },
    { id: 422, name: "Langen" },
    { id: 423, name: "Langenberg" },
    { id: 424, name: "Langenfeld" },
    { id: 425, name: "Langenhagen" },
    { id: 426, name: "Langerwehe" },
    { id: 427, name: "Lauf" },
    { id: 428, name: "Lauterbach" },
    { id: 429, name: "Leer" },
    { id: 430, name: "Legden" },
    { id: 431, name: "Lehrte" },
    { id: 432, name: "Leichlingen" },
    { id: 433, name: "Leimen" },
    { id: 434, name: "Leinfelden-Echterdingen" },
    { id: 435, name: "Leipzig" },
    { id: 436, name: "Lemgo" },
    { id: 437, name: "Lengerich" },
    { id: 438, name: "Lennestadt" },
    { id: 439, name: "Leonberg" },
    { id: 440, name: "Leopoldshöhe" },
    { id: 441, name: "Leverkusen" },
    { id: 442, name: "Lichtenau" },
    { id: 443, name: "Lichtenfels" },
    { id: 444, name: "Lienen" },
    { id: 445, name: "Limburg" },
    { id: 446, name: "Lindau" },
    { id: 447, name: "Lindlar" },
    { id: 448, name: "Lingen" },
    { id: 449, name: "Linnich" },
    { id: 450, name: "Lippetal" },
    { id: 451, name: "Lippstadt" },
    { id: 452, name: "Lohmar" },
    { id: 453, name: "Lohne" },
    { id: 454, name: "Lotte" },
    { id: 455, name: "Luckenwalde" },
    { id: 456, name: "Ludwigsburg" },
    { id: 457, name: "Ludwigsfelde" },
    { id: 458, name: "Ludwigshafen" },
    { id: 459, name: "Löhne" },
    { id: 460, name: "Lörrach" },
    { id: 461, name: "Lübbecke" },
    { id: 462, name: "Lübben" },
    { id: 463, name: "Lübeck" },
    { id: 464, name: "Lüchow" },
    { id: 465, name: "Lüdenscheid" },
    { id: 466, name: "Lüdinghausen" },
    { id: 467, name: "Lügde" },
    { id: 468, name: "Lüneburg" },
    { id: 469, name: "Lünen" },
    { id: 470, name: "Magdeburg" },
    { id: 471, name: "Maintal" },
    { id: 472, name: "Mainz" },
    { id: 473, name: "Mannheim" },
    { id: 474, name: "Marburg" },
    { id: 475, name: "Marienheide" },
    { id: 476, name: "Marienmünster" },
    { id: 477, name: "Marktoberdorf" },
    { id: 478, name: "Marl" },
    { id: 479, name: "Marsberg" },
    { id: 480, name: "Mechernich" },
    { id: 481, name: "Meckenheim" },
    { id: 482, name: "Medebach" },
    { id: 483, name: "Meerbusch" },
    { id: 484, name: "Meinerzhagen" },
    { id: 485, name: "Meiningen" },
    { id: 486, name: "Meißen" },
    { id: 487, name: "Melle" },
    { id: 488, name: "Memmingen" },
    { id: 489, name: "Menden" },
    { id: 490, name: "Meppen" },
    { id: 491, name: "Merseburg" },
    { id: 492, name: "Merzenich" },
    { id: 493, name: "Merzig" },
    { id: 494, name: "Meschede" },
    { id: 495, name: "Metelen" },
    { id: 496, name: "Mettingen" },
    { id: 497, name: "Mettmann" },
    { id: 498, name: "Miesbach" },
    { id: 499, name: "Miltenberg" },
    { id: 500, name: "Mindelheim" },
    { id: 501, name: "Minden" },
    { id: 502, name: "Moers" },
    { id: 503, name: "Monheim am Rhein" },
    { id: 504, name: "Monschau" },
    { id: 505, name: "Montabaur" },
    { id: 506, name: "Morsbach" },
    { id: 507, name: "Mosbach" },
    { id: 508, name: "Much" },
    { id: 509, name: "Munich" },
    { id: 510, name: "Möhnesee" },
    { id: 511, name: "Mönchengladbach" },
    { id: 512, name: "Mörfelden-Walldorf" },
    { id: 513, name: "Mühlacker" },
    { id: 514, name: "Mühldorf" },
    { id: 515, name: "Mühlhausen" },
    { id: 516, name: "Mülheim" },
    { id: 517, name: "Mülheim an der Ruhr" },
    { id: 518, name: "München" },
    { id: 519, name: "Münster" },
    { id: 520, name: "Nachrodt-Wiblingwerde" },
    { id: 521, name: "Naumburg" },
    { id: 522, name: "Neckarsulm" },
    { id: 523, name: "Netphen" },
    { id: 524, name: "Nettersheim" },
    { id: 525, name: "Nettetal" },
    { id: 526, name: "Neu Isenburg" },
    { id: 527, name: "Neu-Ulm" },
    { id: 528, name: "Neubrandenburg" },
    { id: 529, name: "Neuburg" },
    { id: 530, name: "Neuenkirchen" },
    { id: 531, name: "Neuenrade" },
    { id: 532, name: "Neukirchen-Vluyn" },
    { id: 533, name: "Neumarkt" },
    { id: 534, name: "Neumünster" },
    { id: 535, name: "Neunkirchen" },
    { id: 536, name: "Neunkirchen-Seelscheid" },
    { id: 537, name: "Neuruppin" },
    { id: 538, name: "Neuss" },
    { id: 539, name: "Neustadt" },
    { id: 540, name: "Neustadt am Rübenberge" },
    { id: 541, name: "Neustadt-Baden-Württemberg" },
    { id: 542, name: "Neustadt-Bavaria" },
    { id: 543, name: "Neustadt-Hesse" },
    { id: 544, name: "Neuwied" },
    { id: 545, name: "Nideggen" },
    { id: 546, name: "Niederkassel" },
    { id: 547, name: "Niederkrüchten" },
    { id: 548, name: "Niederzier" },
    { id: 549, name: "Nieheim" },
    { id: 550, name: "Nienburg" },
    { id: 551, name: "Norden" },
    { id: 552, name: "Nordenham" },
    { id: 553, name: "Norderstedt" },
    { id: 554, name: "Nordhausen" },
    { id: 555, name: "Nordhorn" },
    { id: 556, name: "Nordkirchen" },
    { id: 557, name: "Nordwalde" },
    { id: 558, name: "Northeim" },
    { id: 559, name: "Nottuln" },
    { id: 560, name: "Nuremberg" },
    { id: 561, name: "Nörvenich" },
    { id: 562, name: "Nümbrecht" },
    { id: 563, name: "Nürnberg" },
    { id: 564, name: "Nürtingen" },
    { id: 565, name: "Oberhausen" },
    { id: 566, name: "Obertshausen" },
    { id: 567, name: "Oberursel" },
    { id: 568, name: "Ochtrup" },
    { id: 569, name: "Odenthal" },
    { id: 570, name: "Oelde" },
    { id: 571, name: "Oer-Erkenschwick" },
    { id: 572, name: "Oerlinghausen" },
    { id: 573, name: "Offenbach" },
    { id: 574, name: "Offenburg" },
    { id: 575, name: "Olching" },
    { id: 576, name: "Oldenburg" },
    { id: 577, name: "Olfen" },
    { id: 578, name: "Olpe" },
    { id: 579, name: "Olsberg" },
    { id: 580, name: "Oranienburg" },
    { id: 581, name: "Osnabrück" },
    { id: 582, name: "Ostbevern" },
    { id: 583, name: "Osterholz-Scharmbeck" },
    { id: 584, name: "Osterode" },
    { id: 585, name: "Ostfildern" },
    { id: 586, name: "Overath" },
    { id: 587, name: "Paderborn" },
    { id: 588, name: "Papenburg" },
    { id: 589, name: "Parchim" },
    { id: 590, name: "Passau" },
    { id: 591, name: "Peine" },
    { id: 592, name: "Perleberg" },
    { id: 593, name: "Petershagen" },
    { id: 594, name: "Pfaffenhofen" },
    { id: 595, name: "Pfarrkirchen" },
    { id: 596, name: "Pforzheim" },
    { id: 597, name: "Pfungstadt" },
    { id: 598, name: "Pinneberg" },
    { id: 599, name: "Pirmasens" },
    { id: 600, name: "Pirna" },
    { id: 601, name: "Plauen" },
    { id: 602, name: "Plettenberg" },
    { id: 603, name: "Plön" },
    { id: 604, name: "Porta Westfalica" },
    { id: 605, name: "Potsdam" },
    { id: 606, name: "Prenzlau" },
    { id: 607, name: "Preußisch Oldendorf" },
    { id: 608, name: "Pulheim" },
    { id: 609, name: "Radebeul" },
    { id: 610, name: "Radevormwald" },
    { id: 611, name: "Radolfzell am Bodensee" },
    { id: 612, name: "Raesfeld" },
    { id: 613, name: "Rahden" },
    { id: 614, name: "Rastatt" },
    { id: 615, name: "Rathenow" },
    { id: 616, name: "Ratingen" },
    { id: 617, name: "Ratzeburg" },
    { id: 618, name: "Ravensburg" },
    { id: 619, name: "Recke" },
    { id: 620, name: "Recklinghausen" },
    { id: 621, name: "Rees" },
    { id: 622, name: "Regen" },
    { id: 623, name: "Regensburg" },
    { id: 624, name: "Reichshof" },
    { id: 625, name: "Reinbek" },
    { id: 626, name: "Reken" },
    { id: 627, name: "Remscheid" },
    { id: 628, name: "Rendsburg" },
    { id: 629, name: "Reutlingen" },
    { id: 630, name: "Rheda-Wiedenbrück" },
    { id: 631, name: "Rhede" },
    { id: 632, name: "Rheinbach" },
    { id: 633, name: "Rheinberg" },
    { id: 634, name: "Rheine" },
    { id: 635, name: "Rheinfelden (Baden)" },
    { id: 636, name: "Rheurdt" },
    { id: 637, name: "Riesa" },
    { id: 638, name: "Rietberg" },
    { id: 639, name: "Rinteln" },
    { id: 640, name: "Rodgau" },
    { id: 641, name: "Roetgen" },
    { id: 642, name: "Rommerskirchen" },
    { id: 643, name: "Rosendahl" },
    { id: 644, name: "Rosenheim" },
    { id: 645, name: "Rostock" },
    { id: 646, name: "Rotenburg" },
    { id: 647, name: "Roth" },
    { id: 648, name: "Rottweil" },
    { id: 649, name: "Rudolstadt" },
    { id: 650, name: "Ruppichteroth" },
    { id: 651, name: "Rödinghausen" },
    { id: 652, name: "Rösrath" },
    { id: 653, name: "Rüthen" },
    { id: 654, name: "Saalfeld" },
    { id: 655, name: "Saarbrücken" },
    { id: 656, name: "Saarlouis" },
    { id: 657, name: "Saerbeck" },
    { id: 658, name: "Salzgitter" },
    { id: 659, name: "Salzkotten" },
    { id: 660, name: "Salzwedel" },
    { id: 661, name: "Sangerhausen" },
    { id: 662, name: "Sankt Augustin" },
    { id: 663, name: "Sankt Ingbert" },
    { id: 664, name: "Sankt Wendel" },
    { id: 665, name: "Sassenberg" },
    { id: 666, name: "Schalksmühle" },
    { id: 667, name: "Schermbeck" },
    { id: 668, name: "Schieder-Schwalenberg" },
    { id: 669, name: "Schlangen" },
    { id: 670, name: "Schleiden" },
    { id: 671, name: "Schleiz" },
    { id: 672, name: "Schleswig" },
    { id: 673, name: "Schloß Holte-Stukenbrock" },
    { id: 674, name: "Schmallenberg" },
    { id: 675, name: "Schorndorf" },
    { id: 676, name: "Schwabach" },
    { id: 677, name: "Schwalmtal" },
    { id: 678, name: "Schwandorf" },
    { id: 679, name: "Schwedt (Oder)" },
    { id: 680, name: "Schweinfurt" },
    { id: 681, name: "Schwelm" },
    { id: 682, name: "Schwerin" },
    { id: 683, name: "Schwerte" },
    { id: 684, name: "Schwäbisch Gmünd" },
    { id: 685, name: "Schwäbisch Hall" },
    { id: 686, name: "Schönebeck" },
    { id: 687, name: "Schöppingen" },
    { id: 688, name: "Seelow" },
    { id: 689, name: "Seelze" },
    { id: 690, name: "Selfkant" },
    { id: 691, name: "Selm" },
    { id: 692, name: "Senden" },
    { id: 693, name: "Sendenhorst" },
    { id: 694, name: "Senftenberg" },
    { id: 695, name: "Siegburg" },
    { id: 696, name: "Siegen" },
    { id: 697, name: "Sigmaringen" },
    { id: 698, name: "Simmerath" },
    { id: 699, name: "Simmern" },
    { id: 700, name: "Sindelfingen" },
    { id: 701, name: "Sinsheim" },
    { id: 702, name: "Soest" },
    { id: 703, name: "Solingen" },
    { id: 704, name: "Sondershausen" },
    { id: 705, name: "Sonneberg" },
    { id: 706, name: "Sonsbeck" },
    { id: 707, name: "Sonthofen" },
    { id: 708, name: "Spenge" },
    { id: 709, name: "Speyer" },
    { id: 710, name: "Springe" },
    { id: 711, name: "Sprockhövel" },
    { id: 712, name: "Stade" },
    { id: 713, name: "Stadthagen" },
    { id: 714, name: "Stadtlohn" },
    { id: 715, name: "Starnberg" },
    { id: 716, name: "Staßfurt" },
    { id: 717, name: "Steinfurt" },
    { id: 718, name: "Steinhagen" },
    { id: 719, name: "Steinheim" },
    { id: 720, name: "Steinheim am Main" },
    { id: 721, name: "Stemwede" },
    { id: 722, name: "Stendal" },
    { id: 723, name: "Stolberg" },
    { id: 724, name: "Straelen" },
    { id: 725, name: "Stralsund" },
    { id: 726, name: "Straubing" },
    { id: 727, name: "Strausberg" },
    { id: 728, name: "Stuttgart" },
    { id: 729, name: "Suhl" },
    { id: 730, name: "Sundern" },
    { id: 731, name: "Swisttal" },
    { id: 732, name: "Sömmerda" },
    { id: 733, name: "Südlohn" },
    { id: 734, name: "Tauberbischofsheim" },
    { id: 735, name: "Taunusstein" },
    { id: 736, name: "Tecklenburg" },
    { id: 737, name: "Telgte" },
    { id: 738, name: "Teltow" },
    { id: 739, name: "Tirschenreuth" },
    { id: 740, name: "Titz" },
    { id: 741, name: "Torgau" },
    { id: 742, name: "Traunstein" },
    { id: 743, name: "Trier" },
    { id: 744, name: "Troisdorf" },
    { id: 745, name: "Tuttlingen" },
    { id: 746, name: "Tönisvorst" },
    { id: 747, name: "Tübingen" },
    { id: 748, name: "Uedem" },
    { id: 749, name: "Uelzen" },
    { id: 750, name: "Ulm" },
    { id: 751, name: "Unna" },
    { id: 752, name: "Unterschleißheim" },
    { id: 753, name: "Vaihingen an der Enz" },
    { id: 754, name: "Vechta" },
    { id: 755, name: "Velbert" },
    { id: 756, name: "Velen" },
    { id: 757, name: "Verden" },
    { id: 758, name: "Verl" },
    { id: 759, name: "Versmold" },
    { id: 760, name: "Vettweiß" },
    { id: 761, name: "Viernheim" },
    { id: 762, name: "Viersen" },
    { id: 763, name: "Villingen-Schwenningen" },
    { id: 764, name: "Vlotho" },
    { id: 765, name: "Voerde" },
    { id: 766, name: "Vreden" },
    { id: 767, name: "Völklingen" },
    { id: 768, name: "Wachtberg" },
    { id: 769, name: "Wachtendonk" },
    { id: 770, name: "Wadersloh" },
    { id: 771, name: "Waiblingen" },
    { id: 772, name: "Waldbröl" },
    { id: 773, name: "Waldfeucht" },
    { id: 774, name: "Waldshut-Tiengen" },
    { id: 775, name: "Waltrop" },
    { id: 776, name: "Wangen im Allgäu" },
    { id: 777, name: "Warburg" },
    { id: 778, name: "Warendorf" },
    { id: 779, name: "Warstein" },
    { id: 780, name: "Wassenberg" },
    { id: 781, name: "Wedel" },
    { id: 782, name: "Weeze" },
    { id: 783, name: "Wegberg" },
    { id: 784, name: "Weiden" },
    { id: 785, name: "Weil am Rhein" },
    { id: 786, name: "Weilerswist" },
    { id: 787, name: "Weilheim" },
    { id: 788, name: "Weimar" },
    { id: 789, name: "Weingarten" },
    { id: 790, name: "Weinheim" },
    { id: 791, name: "Weiterstadt" },
    { id: 792, name: "Weißenburg" },
    { id: 793, name: "Weißenfels" },
    { id: 794, name: "Welver" },
    { id: 795, name: "Wenden" },
    { id: 796, name: "Werdohl" },
    { id: 797, name: "Werl" },
    { id: 798, name: "Wermelskirchen" },
    { id: 799, name: "Werne" },
    { id: 800, name: "Wernigerode" },
    { id: 801, name: "Werther" },
    { id: 802, name: "Wesel" },
    { id: 803, name: "Wesseling" },
    { id: 804, name: "Westerkappeln" },
    { id: 805, name: "Westerstede" },
    { id: 806, name: "Wetter" },
    { id: 807, name: "Wetter (Ruhr)" },
    { id: 808, name: "Wettringen" },
    { id: 809, name: "Wetzlar" },
    { id: 810, name: "Wickede" },
    { id: 811, name: "Wiehl" },
    { id: 812, name: "Wiesbaden" },
    { id: 813, name: "Wiesloch" },
    { id: 814, name: "Wilhelmshaven" },
    { id: 815, name: "Willebadessen" },
    { id: 816, name: "Willich" },
    { id: 817, name: "Wilnsdorf" },
    { id: 818, name: "Windeck" },
    { id: 819, name: "Winnenden" },
    { id: 820, name: "Winsen" },
    { id: 821, name: "Winterberg" },
    { id: 822, name: "Wipperfürth" },
    { id: 823, name: "Wismar" },
    { id: 824, name: "Witten" },
    { id: 825, name: "Wittenberg" },
    { id: 826, name: "Wittlich" },
    { id: 827, name: "Wittmund" },
    { id: 828, name: "Wolfenbüttel" },
    { id: 829, name: "Wolfsburg" },
    { id: 830, name: "Worms" },
    { id: 831, name: "Wunsiedel" },
    { id: 832, name: "Wunstorf" },
    { id: 833, name: "Wuppertal" },
    { id: 834, name: "Wülfrath" },
    { id: 835, name: "Würselen" },
    { id: 836, name: "Würzburg" },
    { id: 837, name: "Xanten" },
    { id: 838, name: "Zeitz" },
    { id: 839, name: "Zirndorf" },
    { id: 840, name: "Zittau" },
    { id: 841, name: "Zweibrücken" },
    { id: 842, name: "Zwickau" },
    { id: 843, name: "Zülpich" },
    { id: 844, name: "Übach-Palenberg" }]),
  // available positions for doctors
  positions: useStorageAsync('positions', [
    { id: 1, name: 'Berufserlaubnis' },
    { id: 2, name: 'Assistenzarzt' },
    { id: 3, name: 'Facharzt' },
    { id: 4, name: 'Oberarzt' },
    { id: 5, name: 'Ltd. Oberarzt' },
    { id: 6, name: 'Chefarzt' }]),
  // form inputs
  form_inputs: useStorageAsync('form_inputs', {
    first_name: '',
    last_name: '',
    email: '',
    phone: '',
    message: '',
  }),
  // location inputs
  location_inputs: {
    city: null,
    state: null,
    radius: null,
    specialization: null,
    position: null,
  },
  // search inputs
  user_inputs: {
    work_life: 0,
    career: 0,
    work_quality: 0,
  },
  // ADMIN STUFF
  slide_over: {
    open: false,
    search_data: undefined
  },
  clinics_slide_over: {
    open: false,
    clinic_form: undefined
  },
  verified_slide_over: {
    open: false,
    clinic_form: undefined
  },
  vacancy_slide_over: {
    open: false,
    data: undefined
  },
  docs_slide_over: {
    open: false,
    data: undefined
  },
  notes: useStorageAsync('notes', []),
});

export { state }